import { NotebookRequest, Template } from "./types";
import { getTemplate } from "./templates";
import path from "path";
import fs from "fs";

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

function renderWritingPage(template: Template): string {
  const { writingPage } = template;
  const { pageSize } = template;

  // Build SVG for the ruled lines
  const lines: string[] = [];
  for (let i = 0; i < writingPage.lineCount; i++) {
    const y = writingPage.firstLineTopOffset + i * writingPage.lineSpacing;
    lines.push(
      `<line x1="${writingPage.lineStartX}" y1="${y}" x2="${writingPage.lineEndX}" y2="${y}" stroke="#000" stroke-width="${writingPage.lineStrokeWidth}" />`
    );
  }

  // Vertical margin line
  const marginLine = `<line x1="${writingPage.marginLineX}" y1="0" x2="${writingPage.marginLineX}" y2="${pageSize.heightPt}" stroke="#000" stroke-width="${writingPage.marginLineStrokeWidth}" />`;

  const svg = `<svg width="${pageSize.widthPt}pt" height="${pageSize.heightPt}pt" xmlns="http://www.w3.org/2000/svg">
    ${lines.join("\n    ")}
    ${marginLine}
  </svg>`;

  return `<section class="page">
    <div class="writing-page">
      ${svg}
    </div>
  </section>`;
}

function renderScripturePage(content: { paragraphs: string[] }, template: Template, language: string): string {
  const { scripturePage } = template;
  const fontFamily = language === "ko" ? "var(--font-noto-serif-kr)" : "var(--font-noto-serif)";

  const paragraphsHtml = content.paragraphs
    .map((para) => `<p>${escapeHtml(para)}</p>`)
    .join("\n      ");

  return `<section class="page">
    <div class="scripture-page" style="
      margin-left: ${scripturePage.marginLeft}pt;
      margin-right: ${scripturePage.marginRight}pt;
      margin-top: ${scripturePage.marginTop}pt;
      margin-bottom: ${scripturePage.marginBottom}pt;
      font-family: ${fontFamily};
    ">
      ${paragraphsHtml}
    </div>
  </section>`;
}

function renderTitlePage(title: string, language: string): string {
  const fontFamily = language === "ko" ? "var(--font-noto-serif-kr)" : "var(--font-noto-serif)";
  return `<section class="page">
    <div class="title-page" style="font-family: ${fontFamily};">
      <h1>${escapeHtml(title)}</h1>
    </div>
  </section>`;
}

function renderBlankPage(): string {
  return `<section class="page">
    <div class="blank-page"></div>
  </section>`;
}

function renderCoverPage(language: string): string {
  const fontFamily = language === "ko" ? "var(--font-noto-serif-kr)" : "var(--font-noto-serif)";
  const title = language === "ko" ? "성경 필사 노트북" : "Bible Transcription Notebook";
  const subtitle = language === "ko" ? "노트북 앱으로 생성됨" : "Generated by the Notebook App";

  return `<section class="page">
    <div class="cover-page" style="font-family: ${fontFamily};">
      <h1>${escapeHtml(title)}</h1>
      <p>${escapeHtml(subtitle)}</p>
    </div>
  </section>`;
}

export function renderNotebookHtml(request: NotebookRequest): string {
  const template = getTemplate(request.templateId);
  const { pageSize } = template;

  const pages: string[] = [];

  // Front matter
  for (const fm of request.frontMatter) {
    if (fm === "blank") {
      pages.push(renderBlankPage());
    } else if (fm === "cover") {
      pages.push(renderCoverPage(request.language));
    }
  }

  // Sections
  for (const section of request.sections) {
    // Title page
    pages.push(renderTitlePage(section.title, request.language));

    // Scripture page + writing page pairs
    for (const pageContent of section.pages) {
      pages.push(renderScripturePage(pageContent, template, request.language));
      pages.push(renderWritingPage(template));
    }
  }

  // Back matter
  for (const bm of request.backMatter) {
    if (bm === "blank") {
      pages.push(renderBlankPage());
    }
  }

  const widthIn = pageSize.widthPt / 72;
  const heightIn = pageSize.heightPt / 72;

  // Load fonts as base64 data URIs
  const fontDir = path.join(process.cwd(), "node_modules");
  const notoSerifPath = path.join(fontDir, "@fontsource/noto-serif/files/noto-serif-latin-400-normal.woff2");
  const notoSerifKrPath = path.join(fontDir, "@fontsource/noto-serif-kr/files/noto-serif-kr-korean-400-normal.woff2");

  let notoSerifBase64 = "";
  let notoSerifKrBase64 = "";

  try {
    if (fs.existsSync(notoSerifPath)) {
      const fontBuffer = fs.readFileSync(notoSerifPath);
      notoSerifBase64 = fontBuffer.toString("base64");
    }
  } catch (error) {
    console.warn("Failed to load Noto Serif font:", error);
  }

  try {
    if (fs.existsSync(notoSerifKrPath)) {
      const fontBuffer = fs.readFileSync(notoSerifKrPath);
      notoSerifKrBase64 = fontBuffer.toString("base64");
    }
  } catch (error) {
    console.warn("Failed to load Noto Serif KR font:", error);
  }

  return `<!DOCTYPE html>
<html lang="${request.language}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bible Transcription Notebook</title>
  <style>
    ${notoSerifBase64 ? `
    @font-face {
      font-family: 'Noto Serif';
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: url(data:font/woff2;base64,${notoSerifBase64}) format('woff2');
    }
    ` : ""}
    ${notoSerifKrBase64 ? `
    @font-face {
      font-family: 'Noto Serif KR';
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: url(data:font/woff2;base64,${notoSerifKrBase64}) format('woff2');
    }
    ` : ""}

    :root {
      --font-noto-serif: ${notoSerifBase64 ? "'Noto Serif', " : ""}serif;
      --font-noto-serif-kr: ${notoSerifKrBase64 ? "'Noto Serif KR', " : ""}serif;
    }

    @page {
      size: ${widthIn}in ${heightIn}in;
      margin: 0;
    }

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: var(--font-noto-serif);
      font-size: 12pt;
      line-height: 1.6;
      color: #000;
    }

    .page {
      width: ${pageSize.widthPt}pt;
      height: ${pageSize.heightPt}pt;
      page-break-after: always;
      position: relative;
      overflow: hidden;
      background: #fff;
    }

    .blank-page {
      width: 100%;
      height: 100%;
    }

    .cover-page {
      width: 100%;
      height: 100%;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
    }

    .cover-page h1 {
      font-size: 32pt;
      margin-bottom: 20pt;
      font-weight: 400;
    }

    .cover-page p {
      font-size: 14pt;
      color: #666;
    }

    .title-page {
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .title-page h1 {
      font-size: 48pt;
      font-weight: 400;
      text-align: center;
      letter-spacing: 0.1em;
    }

    .scripture-page {
      width: 100%;
      height: 100%;
      font-size: 11pt;
      line-height: 1.8;
      text-align: justify;
    }

    .scripture-page p {
      margin-bottom: 12pt;
      text-indent: 0;
    }

    .scripture-page p:first-child {
      margin-top: 0;
    }

    .writing-page {
      width: 100%;
      height: 100%;
      position: relative;
    }

    .writing-page svg {
      display: block;
      width: 100%;
      height: 100%;
    }
  </style>
</head>
<body>
  ${pages.join("\n  ")}
</body>
</html>`;
}
